[package]
name = "gen"
version = "0.1.0"
authors = ["Dave Rolsky <autarch@urth.org>"]
description = "The generator for the dioxus-heroicons code"
repository = "https://github.com/houseabsolute/dioxus-heroicons"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
clap = { version = "4", features = ["derive"] }
heck = "0.4"
itertools = "0.11"
scraper = "0.17"
walkdir = "2"
